version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-full-node:
    image: cudos-start-full-node
    container_name: $CONFIG_VALIDATOR_CONTAINER_NAME
    build:
      dockerfile: CudosBuilders/docker/full-node/start-full-node.dockerfile
      context: ../../../
    restart: unless-stopped
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$VOLUME_NAME:$CUDOS_HOME'
    networks:
      - shared-cudos-network