version: '3.1'

services:
  cudos-full-node-01:
    image: $IMAGE_NAME
    container_name: $CONTAINER_NAME
    build:
      dockerfile: CudosBuilders/docker/full-node/init-full-node.dockerfile
      context: ../../../
      args:
        GENESIS_FILENAME: "$GENESIS_FILENAME"
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$CONTAINER_NAME:$CUDOS_HOME'
