version: '3.1'

services:
  cudos-sentry-node:
    image: cudos-init-sentry-node
    container_name: $INIT_CONTAINER_NAME
    build:
      dockerfile: CudosBuilders/docker/sentry-node/init-sentry-node.dockerfile
      context: ../../../
      args:
        GENESIS_FILENAME: "$GENESIS_FILENAME"
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$VOLUME_NAME:$CUDOS_HOME'
