version: '3.1'

services:
  cudos-sentry-node-01:
    image: cudos-init-sentry-node-01
    container_name: cudos-init-sentry-node-01
    build:
      dockerfile: CudosBuilders/docker/sentry-node/init-sentry-node.dockerfile
      context: ../../../
      args:
        GENESIS_FILENAME: "$GENESIS_FILENAME"
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/cudos-data-sentry-node-01:$CUDOS_HOME'
