version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-sentry-node-01:
    image: cudos-start-sentry-node-01
    container_name: cudos-start-sentry-node-01
    build:
      dockerfile: CudosBuilders/docker/sentry-node/start-sentry-node.dockerfile
      context: ../../../
    restart: unless-stopped
    volumes:
      - '../../../CudosData/cudos-data-sentry-node-01:/usr/cudos/cudos-data'
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
    networks:
      - shared-cudos-network