version: '3.1'

services:
  cudos-root-node:
    image: cudos-init-root-node
    container_name: cudos-init-root-node
    build:
      dockerfile: CudosBuilders/docker/root-node/init-root-node.dockerfile
      context: ../../../
    volumes:
      - '../../../CudosData/cudos-data-root-node:/usr/cudos/cudos-data'